export const ITEMS_FLAG='ITEMS';
export const EMPTY_INVOICE_DETAILS = 'EMPTY_INVOICE_DETAILS';
export const EMPTY_ITEM_DETAILS = 'EMPTY_ITEM_DETAILS';
export const GET_INVOICES = 'GET_INVOICES';
export const GET_ITEMS = 'GET_ITEMS';
export const GET_INVOICE_DETAILS = 'GET_INVOICE_DETAILS';
export const GET_ITEM_DETAILS = 'GET_ITEM_DETAILS';
export const INVOICE_FLAG='INVOICES';

